version: "3.7"
services: 
  web:
    image: yogesh8177/heroes-web-prod:419
    env_file: .env-web
    ports:
      - 8000:8000
    command: node app.js

  voting-service:
    image: yogesh8177/heroes-voting-prod:509
    env_file: .env-voting
    ports: 
      - 3000:3000
    command: npm start
    depends_on: 
      - redis

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose: 
      - 6379