version: "3.7"
networks:
  gateway:
    driver: bridge

services: 
  web: 
    build: 
      context: ./api-service
      dockerfile: ./Dockerfile
    command: npm run start:docker
    environment: 
      - NODE_ENV=github
      - FIELD_INDEXES=id:number,name:string
      - INVERTED_INDEXES=name
      - DEFAULT_SORT_ORDER=asc
    expose:
     - 8000
    networks: 
      - gateway

  voting-service:
    build: 
      context: .
      dockerfile: ./voting-service/Dockerfile
    image: voting-service
    command: node index.js
    environment: 
      - NODE_ENV=github
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
      - PORT=3000
    expose:
      - 3000
    networks: 
      - gateway
    depends_on: 
      - redis
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose: 
      - 6379
    networks: 
      - gateway

  ui:
    build: 
      context: .
      dockerfile: ./ui/Dockerfile
    image: feed-ui
    command: ng serve --configuration=docker --host 0.0.0.0 --disable-host-check
    expose: 
      - 4200
    networks: 
      - gateway
    
  ui-e2e:
    image: feed-ui
    command: dockerize -wait http://web:8000/test --wait http://voting-service:3000/test -wait http://ui:4200 -wait tcp://selenium-chrome-standalone:4444 -timeout 30s -wait-retry-interval 1s bash -c "ng e2e -c docker-e2e"
    depends_on: 
      - ui
      - web
      - selenium-chrome-standalone
    networks: 
      - gateway
  
  selenium-chrome-standalone:
    image: selenium/standalone-chrome
    expose:
      - 4444
    networks: 
      - gateway
    