version: "3.7"
services: 
  web-server: 
    build: .
    command: npm start
    ports:
     - "8000:8000"
    
  ui:
    build: ./ui
    command: ng e2e --protractorConfig=e2e/docker.protractor.conf.js
    depends_on: 
      - web-server
    