version: "3.7"
services: 
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - web
      - voting-service
    ports: 
      - "80:80"
  web:
    image: yogesh8177/heroes-web-prod:640
    env_file: .env-web
    ports:
      - 8000:8000
    command: node app.js

  voting-service:
    image: yogesh8177/heroes-voting-prod:509
    env_file: .env-voting
    ports: 
      - 3000:3000
    command: npm start
    depends_on: 
      - redis

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose: 
      - 6379
