version: "3.7"
networks:
  gateway:
    driver: bridge

services: 
  web: 
    build: .
    command: npm start
    expose:
     - 8000
    networks: 
      - gateway

  ui:
    build: .
      dockerfile: ./ui/Dockerfile
    image: feed-ui
    command: ng serve --host 0.0.0.0 --disable-host-check
    expose: 
      - 4200
    networks: 
      - gateway
    
  ui-e2e:
    image: feed-ui
    #command: ng e2e --protractorConfig=e2e/docker.protractor.conf.js
    command: dockerize -wait http://web:8000/test -wait http://ui:4200 -wait tcp://selenium-chrome-standalone:4444 -timeout 30s -wait-retry-interval 1s bash -c "ng e2e -c docker-e2e"
    depends_on: 
      - ui
      - web
      - selenium-chrome-standalone
    networks: 
      - gateway
  
  selenium-chrome-standalone:
    image: selenium/standalone-chrome
    expose:
      - 4444
    networks: 
      - gateway
    