version: "3.7"
services: 
  web-server: 
    image: yogesh8177/feed-web:latest
    command: npm start
    
  ui:
    image: yogesh8177/feed-ui:latest
    command: ng e2e
    depends_on: 
      - web-server
    