FROM node:14

WORKDIR /feed-web
COPY package*.json ./
RUN npm install
COPY . .

ENV BUILD_TEXT_FILE ./build.txt

RUN rm ${BUILD_TEXT_FILE} && touch ${BUILD_TEXT_FILE} && echo ${BUILD_VERSION} > ${BUILD_TEXT_FILE} 

ENV NODE_ENV production

EXPOSE 8000
CMD [ "node", "server.js" ]