FROM node:14 as Build

COPY ./ /build

WORKDIR /build/api-service

RUN npm install
RUN ls -a && npm run build

FROM node:14
COPY --from=Build /build/api-service/dist /app

WORKDIR /app

ENV BUILD_TEXT_FILE ./build.txt

ARG BUILD_VERSION

RUN rm ${BUILD_TEXT_FILE} && touch ${BUILD_TEXT_FILE} && echo ${BUILD_VERSION} > ${BUILD_TEXT_FILE} 

ENV NODE_ENV production

EXPOSE 8000
CMD [ "node", "app.js" ]