FROM node:14 as Build

COPY ./api-service /build

WORKDIR /build

RUN npm install
RUN npm run build

FROM node:14
COPY --from=Build /build/dist /app

WORKDIR /app

ENV BUILD_TEXT_FILE ./build.txt

ARG BUILD_VERSION

RUN rm ${BUILD_TEXT_FILE} && touch ${BUILD_TEXT_FILE} && echo ${BUILD_VERSION} > ${BUILD_TEXT_FILE} 

ENV NODE_ENV production

EXPOSE 8000
CMD [ "node", "app.js" ]