FROM node:14

WORKDIR /feed-ui
COPY . .

# Install node modules
RUN cd ui && npm install

WORKDIR /feed-ui/ui

# RUN npm run build for production
RUN npm run build:prod
EXPOSE 4200/tcp

# Run the app
CMD [ "npm", "start" ]