# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feed App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-web-server:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./database && npm ci
    - run: cd ./database && npm run build --if-present
    - run: cd ./database && npm test
    - run: npm ci
    - run: npm test
  
  build-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: npm install and npm run build
        run: |
          cd ./ui
          npm ci
          npm run build
  
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run node web server
        run: |
          npm install
          npm start
      - name: run e2e tests
        run: |
          cd ui
          npm install -g @angular/cli
          npm ci
          ./node_modules/protractor/bin/webdriver-manager update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt install ./google-chrome-stable_current_amd64.deb -y
          ng e2e
