# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feed App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-web-server:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        #node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./database && npm ci
    - run: cd ./database && npm run build --if-present
    - run: cd ./database && npm run coverage
    - run: npm ci
    - run: npm run coverage

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: yogesh8177/feed-web
        tags: latest
  
  build-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
  
    steps:
      - uses: actions/checkout@v1
  
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
      # - name: npm install and npm run build
      #   run: |
      #     cd ./ui
      #     npm ci
      #     npm run build
      - name: Run e2e
        run: docker-compose up --exit-code-from ui-e2e
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: yogesh8177/feed-ui
          tags: latest
          context: ./ui
          dockerfile: ./ui/Dockerfile

      

